name: env_for_detection
channels:
  - conda-forge
dependencies:
  - python=3.10.9
  - pip<=22.3.1
  - pip:
      - mlflow==2.3
      - cloudpickle==2.0.0
      - numpy==1.23.5
      - pathlib==1.0.1
      - psutil==5.9.0
      - scikit-learn==1.2.2
      - scipy==1.10.0
